from .day1 import *
from .day2 import *
from .day3 import *
from .day4 import *
from .day5 import *
from .day6 import *
from .day7 import *
from .day8 import *
from .day9 import *
from .day10 import *
